#!/bin/env python3

import hid
import sys

VENDOR_ID = 0x03f0
PRODUCT_ID = 0x098d

def open_device(vendor_id, product_id):
    path = None
    device = hid.device()

    for interface in hid.enumerate(vendor_id, product_id):
        path = interface['path']
        if path:
            device.open_path(path)
            return device

    return None

def main():
    device = open_device(VENDOR_ID, PRODUCT_ID)
    if not device:
        print('error: failed to open device')
        sys.exit(1)
    device.write(b'\x21\xbb\x0b\x00')
    data = device.read(32)
    device.close()

    battery = data[3]
    print(battery)

if __name__ == '__main__':
    main()
